### ISSUE TITLE
Disable log

### ISSUE THREAD

**Issue by furstenheim** [lukpank/go-glpk#7]
Hi,
I'm running go-glpk but it generates a lot of noise to the stdout when solving. Is there a way to disable this?
Thanks

**Comment by lukpank** [comment]
Hi, You can change message level to only display errors:

	lp := glpk.New()
	// ...
	smcp := glpk.NewSmcp()
	smcp.SetMsgLev(glpk.MSG_ERR)
	if err := lp.Simplex(smcp); err != nil {
		// ...
	}

**Comment by furstenheim** [comment]
Hi, Great. Thanks
