### ISSUE TITLE
I'm unable to use this library on an M1 Mac

### ISSUE THREAD

**Issue by pavelnikolov** [lukpank/go-glpk#9]
If I try a normal `go build .` or `go test ./...` command I get the error below:
```
fatal error: glpk.h: No such file or directory #include <glpk.h> #2
```
I have `glpk` installed on my machine:
```
$ glpk
GLPSOL--GLPK LP/MIP Solver 5.0
No input problem file specified; try glpk --help
```

In addition to that I tried downloading the source code of the library and overriding the path to the `glpk.h` file but I get a different error:

```
$ CGO_ENABLED=1 CGO_CFLAGS="-I/path/to/glpk-5.0/src/" go build .
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: library not found for -lglpk
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I have no idea how to proceed. Has anyone had success with using this library on M1 Mac?

**Comment by smrfs** [comment]
Hi @pavelnikolov ,
If you found any solution, kindly please write down here?
I'm trying in M4 Mac, but it does not work for me to install glpk by homebrew...

Thanks!
